// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnalyticsController from "./analytics_controller"
application.register("analytics", AnalyticsController)

import AudioPlayerController from "./audio_player_controller"
application.register("audio-player", AudioPlayerController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PhoneInputController from "./phone_input_controller"
application.register("phone-input", PhoneInputController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TrialUpdatesController from "./trial_updates_controller"
application.register("trial-updates", TrialUpdatesController)

import BusinessUpdatesController from "./business_updates_controller"
application.register("business-updates", BusinessUpdatesController)
