default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "critical,default,low"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
      # Process queues in priority order
      
development:
  <<: *default

test:
  <<: *default
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 0.1

production:
  <<: *default
